package Timer.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Material {
  metal("metal", "metal"),
  wood("wood", "wood"),
  plastic("plastic", "plastic"),
  stone("stone", "stone"),
  glass("glass", "glass");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Material> getConstants() {
    List<Material> list = ListSequence.fromList(new LinkedList<Material>());
    ListSequence.fromList(list).addElement(Material.metal);
    ListSequence.fromList(list).addElement(Material.wood);
    ListSequence.fromList(list).addElement(Material.plastic);
    ListSequence.fromList(list).addElement(Material.stone);
    ListSequence.fromList(list).addElement(Material.glass);
    return list;
  }

  public static Material getDefault() {
    return Material.metal;
  }

  public static Material parseValue(String value) {
    if (value == null) {
      return Material.getDefault();
    }
    if (value.equals(Material.metal.getValueAsString())) {
      return Material.metal;
    }
    if (value.equals(Material.wood.getValueAsString())) {
      return Material.wood;
    }
    if (value.equals(Material.plastic.getValueAsString())) {
      return Material.plastic;
    }
    if (value.equals(Material.stone.getValueAsString())) {
      return Material.stone;
    }
    if (value.equals(Material.glass.getValueAsString())) {
      return Material.glass;
    }
    return Material.getDefault();
  }

  private String myValue;

  Material(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
