package Timer.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum Numerals {
  roman("roman", "roman"),
  arabic("arabic", "arabic");

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return this.myValue;
  }

  public static List<Numerals> getConstants() {
    List<Numerals> list = ListSequence.fromList(new LinkedList<Numerals>());
    ListSequence.fromList(list).addElement(Numerals.roman);
    ListSequence.fromList(list).addElement(Numerals.arabic);
    return list;
  }

  public static Numerals getDefault() {
    return Numerals.roman;
  }

  public static Numerals parseValue(String value) {
    if (value == null) {
      return Numerals.getDefault();
    }
    if (value.equals(Numerals.roman.getValueAsString())) {
      return Numerals.roman;
    }
    if (value.equals(Numerals.arabic.getValueAsString())) {
      return Numerals.arabic;
    }
    return Numerals.getDefault();
  }

  private String myValue;

  Numerals(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }

  public String getValue() {
    return this.myValue;
  }
}
