package Timer.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.openapi.editor.style.Style;
import jetbrains.mps.editor.runtime.style.StyleImpl;
import jetbrains.mps.editor.runtime.style.StyleAttributes;

public class Speaker_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_43oxi_a(editorContext, node);
  }

  private EditorCell createCollection_43oxi_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_43oxi_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_43oxi_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_43oxi_b0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_43oxi_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_43oxi_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_43oxi_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_43oxi_f0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_43oxi_g0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_43oxi_h0(editorContext, node));
    editorCell.addEditorCell(this.createComponent_43oxi_i0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_43oxi_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "speaker");
    editorCell.setCellId("Constant_43oxi_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_43oxi_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "on");
    editorCell.setCellId("Constant_43oxi_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_43oxi_c0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("side");
    provider.setNoTargetText("<no side>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_side");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_43oxi_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "side");
    editorCell.setCellId("Constant_43oxi_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_43oxi_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ",");
    editorCell.setCellId("Constant_43oxi_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_43oxi_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "volume:");
    editorCell.setCellId("Constant_43oxi_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_43oxi_g0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("volume");
    provider.setNoTargetText("<no volume>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_volume");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_43oxi_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "dB");
    editorCell.setCellId("Constant_43oxi_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createComponent_43oxi_i0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = editorContext.getCellFactory().createEditorComponentCell(node, "Timer.editor.FunctionalElement");
    Style style = new StyleImpl();
    style.set(StyleAttributes.INDENT_LAYOUT_ON_NEW_LINE, true);
    style.set(StyleAttributes.INDENT_LAYOUT_INDENT, true);
    editorCell.getStyle().putAll(style);
    return editorCell;
  }
}
