package Timer.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.nodeEditor.EditorManager;

public class SquareShape_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_nnot7o_a(editorContext, node);
  }

  private EditorCell createCollection_nnot7o_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_nnot7o_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_nnot7o_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_nnot7o_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_nnot7o_c0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_nnot7o_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_nnot7o_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_nnot7o_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_nnot7o_g0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_nnot7o_h0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_nnot7o_i0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_nnot7o_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "square");
    editorCell.setCellId("Constant_nnot7o_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_nnot7o_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ",");
    editorCell.setCellId("Constant_nnot7o_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_nnot7o_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "width:");
    editorCell.setCellId("Constant_nnot7o_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_nnot7o_d0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("width");
    provider.setNoTargetText("<no width>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_width");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_nnot7o_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "mm");
    editorCell.setCellId("Constant_nnot7o_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_nnot7o_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "and");
    editorCell.setCellId("Constant_nnot7o_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_nnot7o_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "height:");
    editorCell.setCellId("Constant_nnot7o_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_nnot7o_h0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("height");
    provider.setNoTargetText("<no height>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_height");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createConstant_nnot7o_i0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "mm");
    editorCell.setCellId("Constant_nnot7o_i0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
