package Timer.behavior;

/*Generated by MPS */


public class AnalogDisplay_BehaviorDescriptor extends Display_BehaviorDescriptor {
  public AnalogDisplay_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Timer.structure.AnalogDisplay";
  }
}
