package Timer.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Backlight_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Backlight_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Timer.structure.Backlight";
  }
}
