package Timer.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 8:
        return new Timer_BehaviorDescriptor();
      case 4:
        return new ColorReference_BehaviorDescriptor();
      case 7:
        return new SquareShape_BehaviorDescriptor();
      case 3:
        return new CircularShape_BehaviorDescriptor();
      case 2:
        return new Button_BehaviorDescriptor();
      case 1:
        return new Backlight_BehaviorDescriptor();
      case 6:
        return new Speaker_BehaviorDescriptor();
      case 5:
        return new DigitalDisplay_BehaviorDescriptor();
      case 0:
        return new AnalogDisplay_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"Timer.structure.AnalogDisplay", "Timer.structure.Backlight", "Timer.structure.Button", "Timer.structure.CircularShape", "Timer.structure.ColorReference", "Timer.structure.DigitalDisplay", "Timer.structure.Speaker", "Timer.structure.SquareShape", "Timer.structure.Timer"};
}
