package Timer.behavior;

/*Generated by MPS */


public class CircularShape_BehaviorDescriptor extends Shape_BehaviorDescriptor {
  public CircularShape_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Timer.structure.CircularShape";
  }
}
