package Timer.behavior;

/*Generated by MPS */


public class DigitalDisplay_BehaviorDescriptor extends Display_BehaviorDescriptor {
  public DigitalDisplay_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Timer.structure.DigitalDisplay";
  }
}
