package Timer.behavior;

/*Generated by MPS */


public abstract class Display_BehaviorDescriptor extends FunctionalElement_BehaviorDescriptor {
  public Display_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Timer.structure.Display";
  }
}
