package Timer.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class FunctionalElement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public FunctionalElement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Timer.structure.FunctionalElement";
  }
}
