package Timer.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Shape_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Shape_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Timer.structure.Shape";
  }
}
