package Timer.behavior;

/*Generated by MPS */


public class Speaker_BehaviorDescriptor extends FunctionalElement_BehaviorDescriptor {
  public Speaker_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Timer.structure.Speaker";
  }
}
