package Timer.behavior;

/*Generated by MPS */


public class SquareShape_BehaviorDescriptor extends Shape_BehaviorDescriptor {
  public SquareShape_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Timer.structure.SquareShape";
  }
}
